// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gorecipe

type Ingredient struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	RecipeID int    `json:"recipeId"`
}

type NewIngredient struct {
	Name string `json:"name"`
}

type NewRecipe struct {
	Name      string  `json:"name"`
	Procedure *string `json:"procedure"`
}

type Recipe struct {
	ID          int           `json:"id"`
	Name        string        `json:"name"`
	Procedure   string        `json:"procedure"`
	Ingredients []*Ingredient `json:"ingredients"`
}
